---
abstract: 'A static site generator'
author:
  - 'Doug Bell <preaction@cpan.org>'
build_requires:
  Cwd: 0
  Dir::Self: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::Compile: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statocles
requires:
  Beam::Wire: 0
  File::Basename: 0
  File::Copy::Recursive: 0
  File::Find: 0
  File::Path: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  Git::Repository: 0
  Import::Base: 0
  Mojolicious: 0
  Moo::Lax: 0
  Pod::Usage::Return: 0
  Text::Markdown: 0
  YAML: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/preaction/Statocles/issues
  homepage: https://github.com/preaction/Statocles
  repository: https://github.com/preaction/Statocles.git
version: 0.003
