---
abstract: 'A static site generator'
author:
  - 'Doug Bell <preaction@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Dir::Self: '0'
  Module::Build: '0.3601'
  Test::Compile: '0'
  Test::Deep: '0'
  Test::Differences: '0'
  Test::Exception: '0'
  Test::More: '1.001005'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.023, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Statocles
recommends:
  PPI: '0'
  Pod::Elemental: '0'
  Pod::Weaver: '0'
requires:
  Beam::Wire: '0'
  Encode: '0'
  File::Copy::Recursive: '0'
  File::Share: '0'
  Git::Repository: '0'
  Import::Base: '0.009'
  List::MoreUtils: '0'
  Mojolicious: '5.41'
  Moo::Lax: '0'
  Path::Tiny: '0.054'
  Pod::Usage::Return: '0'
  Text::Markdown: '0'
  Time::Piece: '0'
  Type::Tiny: '0'
  Types::Path::Tiny: '0'
  YAML: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  IRC: irc://irc.perl.org/#statocles
  bugtracker: https://github.com/preaction/Statocles/issues
  homepage: http://preaction.github.io/Statocles
  repository: https://github.com/preaction/Statocles.git
version: '0.030'
x_authority: cpan:PREACTION
