theme:
    class: Statocles::Theme
    args:
        store: site/theme

build:
    class: Statocles::Store
    args:
        path: site/_build

deploy:
    class: Statocles::Store
    args:
        path: .

site:
    class: Statocles::Site::Git
    args:
        title: Statocles
        base_url: http://preaction.github.io/Statocles/
        nav:
            main:
                - title: Blog
                  href: /blog
                - title: Docs
                  href: /pod
        build_store:
            $ref: build
        deploy_store:
            $ref: deploy
        deploy_branch: gh-pages
        index: page
        apps:
            page:
                $class: Statocles::App::Plain
                $args:
                    url_root: /
                    store: site/
                    theme:
                        $ref: theme
            pod:
                $class: Statocles::App::Perldoc
                $args:
                    url_root: /pod
                    inc:
                        - lib/
                    modules:
                        - 'Statocles'
                        - 'Statocles::'
                    index_module: Statocles
                    weave: 1
                    theme:
                        $ref: theme
            blog:
                $class: Statocles::App::Blog
                $args:
                    store:
                        $class: Statocles::Store
                        $args:
                            path: site/blog
                    url_root: /blog
                    theme:
                        $ref: theme
