theme:
    class: Statocles::Theme
    args:
        store: share/theme/default

build:
    class: Statocles::Store
    args:
        path: site/build

deploy:
    class: Statocles::Store
    args:
        path: .

site:
    class: Statocles::Site::Git
    args:
        title: Statocles
        base_url: http://preaction.github.io/Statocles/
        nav:
            main:
                - title: Blog
                  href: /index.html
        build_store:
            $ref: build
        deploy_store:
            $ref: deploy
        deploy_branch: gh-pages
        index: blog
        apps:
            blog:
                $class: Statocles::App::Blog
                $args:
                    store:
                        $class: Statocles::Store
                        $args:
                            path: site/blog
                    url_root: /blog
                    theme:
                        $ref: theme
